import RiemannMachineVerification

/-! Print the foundational axiom dependencies of the headline and its principal proof stages. -/

#print axioms RiemannMachineVerification.headline_correct
#print axioms RiemannMachineVerification.machine278_correct
#print axioms RiemannMachineVerification.Implementation.implementation_iff_arithmetic
#print axioms RiemannMachineVerification.Implementation.machine389_iff_primitive
#print axioms RiemannMachineVerification.Implementation.machine339_iff_machine278
#print axioms RiemannMachineVerification.no_counterexample_below_cutoff
#print axioms RiemannMachineVerification.cutoff_removal
#print axioms RiemannMachineVerification.halts_iff_of_invariant_quotient
#print axioms RiemannMachineVerification.halts_iff_of_local_expansion
#print axioms RiemannMachineVerification.expansion_of_local_check
#print axioms RiemannMachineVerification.integerTest_search_iff
#print axioms RiemannMachineVerification.harmonicLoop_correct
#print axioms RiemannMachineVerification.lcmSearch_initialized
#print axioms RiemannMachineVerification.source_correct
#print axioms RiemannMachineVerification.compiled_cycle
#print axioms RiemannMachineVerification.macro_iff_source
#print axioms RiemannMachineVerification.Implementation.primitive_iff_macro
#print axioms RiemannMachineVerification.Implementation.machine389_iff_machine339
