import RiemannMachineVerification.MacroChecks00
import RiemannMachineVerification.MacroChecks01
import RiemannMachineVerification.MacroChecks02
import RiemannMachineVerification.MacroChecks03
import RiemannMachineVerification.MacroChecks04
import RiemannMachineVerification.MacroChecks05
import RiemannMachineVerification.MacroChecks06
import RiemannMachineVerification.MacroChecks07
import RiemannMachineVerification.MacroChecks08
import RiemannMachineVerification.MacroChecks09
import RiemannMachineVerification.MacroChecks10
import RiemannMachineVerification.MacroChecks11
import RiemannMachineVerification.MacroChecks12
import RiemannMachineVerification.MacroChecks13
import RiemannMachineVerification.MacroChecks14
import RiemannMachineVerification.MacroChecks15
import RiemannMachineVerification.MacroChecks16
import RiemannMachineVerification.MacroChecks17

namespace RiemannMachineVerification

theorem all_macro_checks : ∀ q : Fin 342, MacroCheckFor q := by
  intro q
  fin_cases q
  · exact macro_check_0
  · exact macro_check_1
  · exact macro_check_2
  · exact macro_check_3
  · exact macro_check_4
  · exact macro_check_5
  · exact macro_check_6
  · exact macro_check_7
  · exact macro_check_8
  · exact macro_check_9
  · exact macro_check_10
  · exact macro_check_11
  · exact macro_check_12
  · exact macro_check_13
  · exact macro_check_14
  · exact macro_check_15
  · exact macro_check_16
  · exact macro_check_17
  · exact macro_check_18
  · exact macro_check_19
  · exact macro_check_20
  · exact macro_check_21
  · exact macro_check_22
  · exact macro_check_23
  · exact macro_check_24
  · exact macro_check_25
  · exact macro_check_26
  · exact macro_check_27
  · exact macro_check_28
  · exact macro_check_29
  · exact macro_check_30
  · exact macro_check_31
  · exact macro_check_32
  · exact macro_check_33
  · exact macro_check_34
  · exact macro_check_35
  · exact macro_check_36
  · exact macro_check_37
  · exact macro_check_38
  · exact macro_check_39
  · exact macro_check_40
  · exact macro_check_41
  · exact macro_check_42
  · exact macro_check_43
  · exact macro_check_44
  · exact macro_check_45
  · exact macro_check_46
  · exact macro_check_47
  · exact macro_check_48
  · exact macro_check_49
  · exact macro_check_50
  · exact macro_check_51
  · exact macro_check_52
  · exact macro_check_53
  · exact macro_check_54
  · exact macro_check_55
  · exact macro_check_56
  · exact macro_check_57
  · exact macro_check_58
  · exact macro_check_59
  · exact macro_check_60
  · exact macro_check_61
  · exact macro_check_62
  · exact macro_check_63
  · exact macro_check_64
  · exact macro_check_65
  · exact macro_check_66
  · exact macro_check_67
  · exact macro_check_68
  · exact macro_check_69
  · exact macro_check_70
  · exact macro_check_71
  · exact macro_check_72
  · exact macro_check_73
  · exact macro_check_74
  · exact macro_check_75
  · exact macro_check_76
  · exact macro_check_77
  · exact macro_check_78
  · exact macro_check_79
  · exact macro_check_80
  · exact macro_check_81
  · exact macro_check_82
  · exact macro_check_83
  · exact macro_check_84
  · exact macro_check_85
  · exact macro_check_86
  · exact macro_check_87
  · exact macro_check_88
  · exact macro_check_89
  · exact macro_check_90
  · exact macro_check_91
  · exact macro_check_92
  · exact macro_check_93
  · exact macro_check_94
  · exact macro_check_95
  · exact macro_check_96
  · exact macro_check_97
  · exact macro_check_98
  · exact macro_check_99
  · exact macro_check_100
  · exact macro_check_101
  · exact macro_check_102
  · exact macro_check_103
  · exact macro_check_104
  · exact macro_check_105
  · exact macro_check_106
  · exact macro_check_107
  · exact macro_check_108
  · exact macro_check_109
  · exact macro_check_110
  · exact macro_check_111
  · exact macro_check_112
  · exact macro_check_113
  · exact macro_check_114
  · exact macro_check_115
  · exact macro_check_116
  · exact macro_check_117
  · exact macro_check_118
  · exact macro_check_119
  · exact macro_check_120
  · exact macro_check_121
  · exact macro_check_122
  · exact macro_check_123
  · exact macro_check_124
  · exact macro_check_125
  · exact macro_check_126
  · exact macro_check_127
  · exact macro_check_128
  · exact macro_check_129
  · exact macro_check_130
  · exact macro_check_131
  · exact macro_check_132
  · exact macro_check_133
  · exact macro_check_134
  · exact macro_check_135
  · exact macro_check_136
  · exact macro_check_137
  · exact macro_check_138
  · exact macro_check_139
  · exact macro_check_140
  · exact macro_check_141
  · exact macro_check_142
  · exact macro_check_143
  · exact macro_check_144
  · exact macro_check_145
  · exact macro_check_146
  · exact macro_check_147
  · exact macro_check_148
  · exact macro_check_149
  · exact macro_check_150
  · exact macro_check_151
  · exact macro_check_152
  · exact macro_check_153
  · exact macro_check_154
  · exact macro_check_155
  · exact macro_check_156
  · exact macro_check_157
  · exact macro_check_158
  · exact macro_check_159
  · exact macro_check_160
  · exact macro_check_161
  · exact macro_check_162
  · exact macro_check_163
  · exact macro_check_164
  · exact macro_check_165
  · exact macro_check_166
  · exact macro_check_167
  · exact macro_check_168
  · exact macro_check_169
  · exact macro_check_170
  · exact macro_check_171
  · exact macro_check_172
  · exact macro_check_173
  · exact macro_check_174
  · exact macro_check_175
  · exact macro_check_176
  · exact macro_check_177
  · exact macro_check_178
  · exact macro_check_179
  · exact macro_check_180
  · exact macro_check_181
  · exact macro_check_182
  · exact macro_check_183
  · exact macro_check_184
  · exact macro_check_185
  · exact macro_check_186
  · exact macro_check_187
  · exact macro_check_188
  · exact macro_check_189
  · exact macro_check_190
  · exact macro_check_191
  · exact macro_check_192
  · exact macro_check_193
  · exact macro_check_194
  · exact macro_check_195
  · exact macro_check_196
  · exact macro_check_197
  · exact macro_check_198
  · exact macro_check_199
  · exact macro_check_200
  · exact macro_check_201
  · exact macro_check_202
  · exact macro_check_203
  · exact macro_check_204
  · exact macro_check_205
  · exact macro_check_206
  · exact macro_check_207
  · exact macro_check_208
  · exact macro_check_209
  · exact macro_check_210
  · exact macro_check_211
  · exact macro_check_212
  · exact macro_check_213
  · exact macro_check_214
  · exact macro_check_215
  · exact macro_check_216
  · exact macro_check_217
  · exact macro_check_218
  · exact macro_check_219
  · exact macro_check_220
  · exact macro_check_221
  · exact macro_check_222
  · exact macro_check_223
  · exact macro_check_224
  · exact macro_check_225
  · exact macro_check_226
  · exact macro_check_227
  · exact macro_check_228
  · exact macro_check_229
  · exact macro_check_230
  · exact macro_check_231
  · exact macro_check_232
  · exact macro_check_233
  · exact macro_check_234
  · exact macro_check_235
  · exact macro_check_236
  · exact macro_check_237
  · exact macro_check_238
  · exact macro_check_239
  · exact macro_check_240
  · exact macro_check_241
  · exact macro_check_242
  · exact macro_check_243
  · exact macro_check_244
  · exact macro_check_245
  · exact macro_check_246
  · exact macro_check_247
  · exact macro_check_248
  · exact macro_check_249
  · exact macro_check_250
  · exact macro_check_251
  · exact macro_check_252
  · exact macro_check_253
  · exact macro_check_254
  · exact macro_check_255
  · exact macro_check_256
  · exact macro_check_257
  · exact macro_check_258
  · exact macro_check_259
  · exact macro_check_260
  · exact macro_check_261
  · exact macro_check_262
  · exact macro_check_263
  · exact macro_check_264
  · exact macro_check_265
  · exact macro_check_266
  · exact macro_check_267
  · exact macro_check_268
  · exact macro_check_269
  · exact macro_check_270
  · exact macro_check_271
  · exact macro_check_272
  · exact macro_check_273
  · exact macro_check_274
  · exact macro_check_275
  · exact macro_check_276
  · exact macro_check_277
  · exact macro_check_278
  · exact macro_check_279
  · exact macro_check_280
  · exact macro_check_281
  · exact macro_check_282
  · exact macro_check_283
  · exact macro_check_284
  · exact macro_check_285
  · exact macro_check_286
  · exact macro_check_287
  · exact macro_check_288
  · exact macro_check_289
  · exact macro_check_290
  · exact macro_check_291
  · exact macro_check_292
  · exact macro_check_293
  · exact macro_check_294
  · exact macro_check_295
  · exact macro_check_296
  · exact macro_check_297
  · exact macro_check_298
  · exact macro_check_299
  · exact macro_check_300
  · exact macro_check_301
  · exact macro_check_302
  · exact macro_check_303
  · exact macro_check_304
  · exact macro_check_305
  · exact macro_check_306
  · exact macro_check_307
  · exact macro_check_308
  · exact macro_check_309
  · exact macro_check_310
  · exact macro_check_311
  · exact macro_check_312
  · exact macro_check_313
  · exact macro_check_314
  · exact macro_check_315
  · exact macro_check_316
  · exact macro_check_317
  · exact macro_check_318
  · exact macro_check_319
  · exact macro_check_320
  · exact macro_check_321
  · exact macro_check_322
  · exact macro_check_323
  · exact macro_check_324
  · exact macro_check_325
  · exact macro_check_326
  · exact macro_check_327
  · exact macro_check_328
  · exact macro_check_329
  · exact macro_check_330
  · exact macro_check_331
  · exact macro_check_332
  · exact macro_check_333
  · exact macro_check_334
  · exact macro_check_335
  · exact macro_check_336
  · exact macro_check_337
  · exact macro_check_338
  · exact macro_check_339
  · exact macro_check_340
  · exact macro_check_341

end RiemannMachineVerification
